### ISSUE TITLE
RepairTimeLimit value in minute instead of hour? 

### ISSUE THREAD

**Issue by Aftersky** [mrmin123/kancolle-auto#107]
It would be useful for low level submarines with short repair time.

**Comment by mrmin123** [comment]
I'll try to incorporate both hour and minute into the repair time limit.

**Comment by mrmin123** [comment]
@Aftersky this is addressed in the highly experimental 104_submarine_switch branch, but you can incorporate the change into your local build using the changes in commit a4a9c88. New format in config is HHMM.

**Comment by Aftersky** [comment]
Thanks for implementing it. I gave the experimental branch a try, the script crash as soon as it start using default config:

```
[error] script stopped with error in line 4
[error] SyntaxError ( !!WHILE IMPORTING!! mismatched input '=' expecting COLON (
combat.py, line 346) )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)
```

**Comment by n0k0m3** [comment]
Syntax error => you should try to review the code in combat.py, line346
(use notepad++ for easier editing)

**Comment by mrmin123** [comment]
@Aftersky I've updated the branch to rectify the issue. There might be a lot of other crashes, however, as I haven't even run this branch in Sikuli... it's just a big code dump I did... ;;

Also, please leave issues regarding the branch in #104, thanks!
