### ISSUE TITLE
Problem App.focus Kancollerviewer

### ISSUE THREAD

**Issue by Zhamarr** [mrmin123/kancolle-auto#158]
Hello, I'm pretty new to this so I should just put one the screenshot of  it says in the cmd window.
- kancolle-auto last 
- Viewer/browser: Kancolle viewer

![](http://i.imgur.com/iCUntUF.png)

![](http://i.imgur.com/BPd7eEd.png)
#### Console log

C:\WINDOWS\system32>java -jar C:\Users\nalgagrande\Downloads\Sikuli\sikuli-script.jar -r C:\Users\nalgagrande\Downloads\kancolle-auto-master\kancolle-auto-master\kancolle_auto.sikuli
[2016-04-08 20:19:46] Reading config file
[2016-04-08 20:19:46] Expeditions (fleet 2: 2, fleet 3: 4, fleet 4: 5) enabled!
[2016-04-08 20:19:46] Config loaded!
[2016-04-08 20:19:46] Reading config file
[2016-04-08 20:19:46] Starting kancolle_auto
[2016-04-08 20:19:46] Finding window!
[2016-04-08 20:19:46] Focus on KanColle!
[log] App.focus KanColleViewer!(0) #0
[error] script stopped with error in line 486
[error] AttributeError ( 'NoneType' object has no attribute 'x' )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(JythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScriptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunner.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunner.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)

**Comment by mrmin123** [comment]
Does kancolle-auto actually focus on/bring forward your KCV window before crashing?

**Comment by Zhamarr** [comment]
yes, Kancolle-auto focus on KCV and after Crash :/ i try to change the "zoom" but not work

**Comment by mrmin123** [comment]
Ultimately kancolle-auto cannot ensure that it's found the correct window because it couldn't find anything that matches the image `menu_main_home.png` in the window you specified. `menu_main_home.png` is supposed to be the upper-right corner of the big circular button in the upper-left corner of the game screen. If you can't find that image, or if you find that it doesn't match due to zoom/scale, then kancolle-auto will crash.

**Comment by mrmin123** [comment]
Ticket #156 might be relevant.
