### ISSUE TITLE
Sortie stuck on compass

### ISSUE THREAD

**Issue by CyberAquila** [mrmin123/kancolle-auto#171]
Hi, I'm currently using the latest release. There seems to be a persistent issue where it gets stuck on sortieing for 3-2A because it doesn't click the compass.
Here's a Log:

←[94m[2016-05-24 02:47:05] Refreshing home with 0 or less sidestep(s)!←[0m
[log] CLICK on L(457,406)@S(0)[0,0 1366x768]
[log] CLICK on L(239,310)@S(0)[0,0 1366x768]
←[94m[2016-05-24 02:47:13] Navigating to combat menu with 0 sidestep(s)!←[0m
[log] CLICK on L(319,278)@S(0)[0,0 1366x768]
[log] CLICK on L(377,308)@S(0)[0,0 1366x768]
[log] CLICK on L(454,505)@S(0)[0,0 1366x768]
[log] CLICK on L(814,277)@S(0)[0,0 1366x768]
[log] CLICK on L(849,515)@S(0)[0,0 1366x768]
←[94m[2016-05-24 02:47:34] Checking fleet condition...←[0m
←[94m[2016-05-24 02:47:44] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
←[92m[2016-05-24 02:47:53] Commencing sortie!←[0m
[log] CLICK on L(834,486)@S(0)[0,0 1366x768]
[error] script stopped with error in line 557
[error] TypeError ( not all arguments converted during string formatting )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)

**Comment by qwe8585** [comment]
Happened too me too. Swiched back to r3 no issues.

**Comment by mrmin123** [comment]
Probably something related to the support of additional sortie rewards I
added in r4. Thanks for the heads up.

**Comment by mrmin123** [comment]
Fixed in [r4.1](https://github.com/mrmin123/kancolle-auto/releases/tag/4.1)
