### ISSUE TITLE
Repair repairs in combat module

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#22]
Has issues when dealing with multiple ships that need to be repaired.

Also when buckets are used.

**Comment by kevin01523** [comment]
```
[debug] ensei_start.png has appeared.
[debug] waiting for ensei_start.png to appear
[debug] ensei_start.png has appeared.
[log] CLICK on L(908,584)@S(0)[0,0 1366x768]
[debug] waiting for exp_started.png to appear
[debug] exp_started.png has appeared.
←[92m[2015-09-28 17:37:16] Expedition sent!: Expedition 2 (ETA 2015-09-28 18:06:
41)←[0m
←[94m[2015-09-28 17:37:18] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:37:26] Going Home!←[0m
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(354,397)@S(0)[0,0 1366x768]
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
←[92m[2015-09-28 17:37:29] At Home!←[0m
←[94m[2015-09-28 17:37:29] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:37:33] No, no fleets to receive!←[0m
←[94m[2015-09-28 17:37:33] Navigating to Sortie menu!←[0m
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(482,407)@S(0)[0,0 1366x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(516,377)@S(0)[0,0 1366x768]
[debug] waiting for combat_area_3.png to appear
[debug] combat_area_3.png has appeared.
[debug] waiting for combat_area_3.png to appear
[debug] combat_area_3.png has appeared.
[log] CLICK on L(591,582)@S(0)[0,0 1366x768]
[debug] waiting for combat_panel_3-2.png to appear
[debug] combat_panel_3-2.png has appeared.
[debug] waiting for combat_panel_3-2.png to appear
[debug] combat_panel_3-2.png has appeared.
[log] CLICK on L(878,344)@S(0)[0,0 1366x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(968,582)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:37:49] Checking fleet condition...←[0m
←[94m[2015-09-28 17:37:59] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
←[92m[2015-09-28 17:38:10] Commencing sortie!←[0m
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(913,583)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(619,384)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:38:34] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.99 to appear
[debug] P(formation_line_ahead.png) S: 0.99 has appeared.
[log] CLICK on L(730,323)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:38:47] Selecting fleet formation!←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1036,570)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:40:12] Checking fleet condition...←[0m
←[94m[2015-09-28 17:40:22] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1036,570)@S(0)[0,0 1366x768]
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[log] CLICK on L(1043,579)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:40:45] Ran the required number of nodes. Falling back!←[0m
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[log] CLICK on L(791,388)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:40:46] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-09-28 17:40:54] At Home!←[0m
←[94m[2015-09-28 17:40:54] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:40:58] No, no fleets to receive!←[0m
←[92m[2015-09-28 17:40:58] Refreshing Home!←[0m
[debug] waiting for supply_main.png to appear
[debug] supply_main.png has appeared.
[log] CLICK on L(360,362)@S(0)[0,0 1366x768]
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(354,397)@S(0)[0,0 1366x768]
←[92m[2015-09-28 17:41:05] At Home!←[0m
←[94m[2015-09-28 17:41:05] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:41:09] No, no fleets to receive!←[0m
←[94m[2015-09-28 17:41:09] Lets resupply fleets!←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for supply_main.png to appear
[debug] supply_main.png has appeared.
[log] CLICK on L(360,362)@S(0)[0,0 1366x768]
[debug] waiting for supply_screen.png to appear
[debug] supply_screen.png has appeared.
[debug] waiting for supply_all.png to appear
[debug] supply_all.png has appeared.
[log] CLICK on L(401,260)@S(0)[0,0 1366x768]
[debug] waiting for supply_available.png to appear
[debug] supply_available.png has appeared.
[debug] waiting for supply_available.png to appear
[debug] supply_available.png has appeared.
[log] CLICK on L(985,580)@S(0)[0,0 1366x768]
[debug] waiting for supply_not_available.png to appear
[debug] supply_not_available.png has appeared.
←[92m[2015-09-28 17:41:25] Done resupplying!←[0m
←[94m[2015-09-28 17:41:25] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:41:34] Going Home!←[0m
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(354,397)@S(0)[0,0 1366x768]
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
←[92m[2015-09-28 17:41:37] At Home!←[0m
←[94m[2015-09-28 17:41:37] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:41:41] No, no fleets to receive!←[0m
←[92m[2015-09-28 17:41:42] Next sortie!: 2015-09-28 17:42:45←[0m
←[94m[2015-09-28 17:41:42] Initial checks and commands complete. Starting loop.←
[0m
←[94m[2015-09-28 17:41:42] Next action at 2015-09-28 17:42:45←[0m
←[94m[2015-09-28 17:42:50] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-09-28 17:42:58] At Home!←[0m
←[94m[2015-09-28 17:42:58] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:43:02] No, no fleets to receive!←[0m
←[92m[2015-09-28 17:43:02] Refreshing Home!←[0m
[debug] waiting for quests_main.png to appear
[debug] quests_main.png has appeared.
[log] CLICK on L(844,191)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(341,589)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(341,589)@S(0)[0,0 1366x768]
←[92m[2015-09-28 17:43:24] At Home!←[0m
←[94m[2015-09-28 17:43:24] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:43:28] No, no fleets to receive!←[0m
←[94m[2015-09-28 17:43:28] Navigating to Sortie menu!←[0m
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(482,407)@S(0)[0,0 1366x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(516,377)@S(0)[0,0 1366x768]
[debug] waiting for combat_area_3.png to appear
[debug] combat_area_3.png has appeared.
[debug] waiting for combat_area_3.png to appear
[debug] combat_area_3.png has appeared.
[log] CLICK on L(591,582)@S(0)[0,0 1366x768]
[debug] waiting for combat_panel_3-2.png to appear
[debug] combat_panel_3-2.png has appeared.
[debug] waiting for combat_panel_3-2.png to appear
[debug] combat_panel_3-2.png has appeared.
[log] CLICK on L(878,344)@S(0)[0,0 1366x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(968,582)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:43:44] Checking fleet condition...←[0m
←[94m[2015-09-28 17:43:54] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
←[92m[2015-09-28 17:44:03] Commencing sortie!←[0m
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(913,583)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(619,384)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:44:25] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.99 to appear
[debug] P(formation_line_ahead.png) S: 0.99 has appeared.
[log] CLICK on L(730,323)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:44:38] Selecting fleet formation!←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1036,570)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:46:27] Checking fleet condition...←[0m
←[94m[2015-09-28 17:46:35] Light damage: 0; moderate damage: 0; critical damage:
 1←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1036,570)@S(0)[0,0 1366x768]
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[log] CLICK on L(1043,579)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:46:57] Ran the required number of nodes. Falling back!←[0m
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[log] CLICK on L(791,388)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:46:58] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-09-28 17:47:05] At Home!←[0m
←[94m[2015-09-28 17:47:05] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:47:09] No, no fleets to receive!←[0m
←[92m[2015-09-28 17:47:09] Refreshing Home!←[0m
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(482,407)@S(0)[0,0 1366x768]
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(354,397)@S(0)[0,0 1366x768]
←[92m[2015-09-28 17:47:15] At Home!←[0m
←[94m[2015-09-28 17:47:15] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-28 17:47:19] No, no fleets to receive!←[0m
←[94m[2015-09-28 17:47:19] Navigating to Repair menu!←[0m
[debug] waiting for repair_main.png to appear
[debug] repair_main.png has appeared.
[log] CLICK on L(406,502)@S(0)[0,0 1366x768]
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[log] CLICK on L(537,384)@S(0)[0,0 1366x768]
←[94m[2015-09-28 17:47:29] Check for critically damaged ships.←[0m
[debug] waiting for P(repair_dmg_critical.png) S: 0.95 to appear
[debug] P(repair_dmg_critical.png) S: 0.95 has appeared.
[log] CLICK on L(1017,279)@S(0)[0,0 1366x768]
←[92m[2015-09-28 17:47:29] Starting repair on critically damaged ship!←[0m
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has appeared.
[debug] OCR data path: D:/sikuli/libs/
[debug] TextRecognizer: inited.
[debug] Region.text: #(30)#
[error] script stopped with error in line 342
[error] IndexError ( list assignment index out of range )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181
```

got this just now i dont know if this is related but i have onw ship critically damaged then it crashed

**Comment by mrmin123** [comment]
I've never had an issue with single ship repairs. I'm going to spend a few days to try and fix/improve multi-ship repairs and hopefully that'll resolve the issue you're seeing. If it only happens once in a while I'd say just ignore and restart script.

**Comment by kevin01523** [comment]
yep happens once in a while actually 2 times it happened yestterday and just now w/ the exact same error

**Comment by kevin01523** [comment]
[2015-10-04 10:15:56] At Home!
[2015-10-04 10:15:56] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-04 10:16:01] No, no fleets to receive!
[2015-10-04 10:16:01] Navigating to Repair menu!
[debug] waiting for repair_main.png to appear
[debug] repair_main.png has appeared.
[log] CLICK on L(435,440)@S(0)[0,0 1360x768]
[error] script stopped with error in line 349
[error] FindFailed ( can not find repair_empty.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
214: combat (  go_repair )     for i in self.kc_window.findAll('repair_empty.png'):
247: main (  sortie_action )     combat_item.go_repair()
[error] --- Traceback --- end --------------
this happens if docks is full when script tries to repair ship

**Comment by mrmin123** [comment]
Were your repair docks already full before you started the script?

**Comment by kevin01523** [comment]
uhm yes im checking the script response on a what if situation where if docks are full

**Comment by mrmin123** [comment]
Ah, ok. Yea, I think a 'requirement' of the script in its current state is that at least one repair dock be empty for use. It's a bit more work to incorporate checking repair times for the docks (currently the script grabs them before starting repairs because it's easier...) and I don't think I can get to it any time soon.

On a related note, testing the repair functionality is the hardest because of how much time is involved in repairs... so annoying

**Comment by kevin01523** [comment]
well atleast some of the problems were fixed before i can post it here on the last update idk if its fixed but the script sometimes get stuck if i end on the rsc node on orel

**Comment by mrmin123** [comment]
Yes, the script freezing when ending on a resource node should be fixed on the latest push of the 22_repairs branch. Thanks for all your testing btw!

**Comment by kevin01523** [comment]
[2015-10-04 13:56:55] Ship(s) in condition at or below threshold! Ceasing sortie!
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[log] CLICK on L(815,374)@S(0)[0,0 1360x768]
[2015-10-04 13:56:57] Focus on KanColle!
[log] App.focus Google Chrome(0) #0
[log] switchApp: Google Chrome
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-04 13:57:08] At Home!
[2015-10-04 13:57:08] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-04 13:57:14] No, no fleets to receive!
[2015-10-04 13:57:14] Refreshing Home!
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[log] CLICK on L(469,176)@S(0)[0,0 1360x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(364,579)@S(0)[0,0 1360x768]
[2015-10-04 13:57:34] At Home!
[2015-10-04 13:57:34] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-04 13:57:39] No, no fleets to receive!
[2015-10-04 13:57:39] Navigating to Repair menu!
[debug] waiting for repair_main.png to appear
[debug] repair_main.png has appeared.
[log] CLICK on L(430,488)@S(0)[0,0 1360x768]
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[log] CLICK on L(561,289)@S(0)[0,0 1360x768]
[2015-10-04 13:57:50] Check for critically damaged ships.
[debug] waiting for P(repair_dmg_critical.png) S: 0.95 to appear
[debug] P(repair_dmg_critical.png) S: 0.95 has appeared.
[log] CLICK on L(1041,265)@S(0)[0,0 1360x768]
[2015-10-04 13:57:53] Starting repair on critically damaged ship!
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has appeared.
[debug] Region.text: #(0|:55210)#
[error] script stopped with error in line 349
[error] ValueError ( invalid literal for int() with base 10: 0| )
[error] --- Traceback --- error source first
line: module ( function ) statement 
241: combat (  go_repair )     if int(repair_timer[0:2]) >= self.repair_time_limit:
247: main (  sortie_action )     combat_item.go_repair()
[error] --- Traceback --- end --------------

hmm this seems to be a bug on declaration or something?

**Comment by mrmin123** [comment]
No, that's the OCR acting up... it looks like it recognized '01:55:10' as '0|:55210'. Another character to add to my OCR check function...

**Comment by kevin01523** [comment]
ok i fixed that using the tessdata provided by ubuntu then this one maybe a bug

```
←[92m[2015-10-07 12:36:46] At Home!←[0m
←[94m[2015-10-07 12:36:46] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-07 12:36:50] No, no fleets to receive!←[0m
←[94m[2015-10-07 12:36:50] Navigating to Sortie menu!←[0m
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(510,400)@S(0)[0,0 1366x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(544,370)@S(0)[0,0 1366x768]
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[log] CLICK on L(544,572)@S(0)[0,0 1366x768]
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[log] CLICK on L(571,481)@S(0)[0,0 1366x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(996,575)@S(0)[0,0 1366x768]
←[94m[2015-10-07 12:37:05] Checking fleet condition...←[0m
←[94m[2015-10-07 12:37:12] Light damage: 1; moderate damage: 0; critical damage:
 0←[0m
←[94m[2015-10-07 12:37:18] Checking fleet morale!←[0m
←[92m[2015-10-07 12:37:25] Ships have good morale!←[0m
←[92m[2015-10-07 12:37:28] Commencing sortie!←[0m
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(941,576)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(647,377)@S(0)[0,0 1366x768]
←[94m[2015-10-07 12:37:57] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.99 to appear
[debug] P(formation_line_ahead.png) S: 0.99 has appeared.
[log] CLICK on L(758,316)@S(0)[0,0 1366x768]
←[94m[2015-10-07 12:38:10] Selecting fleet formation!←[0m
←[94m[2015-10-07 12:39:13] Declining night battle!←[0m
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(603,371)@S(0)[0,0 1366x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1064,563)@S(0)[0,0 1366x768]
←[94m[2015-10-07 12:39:31] Checking fleet condition...←[0m
←[94m[2015-10-07 12:39:36] Light damage: 0; moderate damage: 1; critical damage:
 1←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1064,563)@S(0)[0,0 1366x768]
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[log] CLICK on L(1071,572)@S(0)[0,0 1366x768]
←[93m[2015-10-07 12:40:05] Ship(s) in condition at or below threshold! Ceasing s
ortie!←[0m
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has appeared.
[log] CLICK on L(819,381)@S(0)[0,0 1366x768]
←[94m[2015-10-07 12:40:06] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-10-07 12:40:13] At Home!←[0m
←[94m[2015-10-07 12:40:13] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-07 12:40:18] No, no fleets to receive!←[0m
←[92m[2015-10-07 12:40:18] Refreshing Home!←[0m
[debug] waiting for repair_main.png to appear
[debug] repair_main.png has appeared.
[log] CLICK on L(434,495)@S(0)[0,0 1366x768]
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(382,390)@S(0)[0,0 1366x768]
←[92m[2015-10-07 12:40:24] At Home!←[0m
←[94m[2015-10-07 12:40:24] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-07 12:40:28] No, no fleets to receive!←[0m
←[94m[2015-10-07 12:40:28] Navigating to Repair menu!←[0m
[debug] waiting for repair_main.png to appear
[debug] repair_main.png has appeared.
[log] CLICK on L(434,495)@S(0)[0,0 1366x768]
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[log] CLICK on L(565,377)@S(0)[0,0 1366x768]
←[94m[2015-10-07 12:40:36] Check for critically damaged ships.←[0m
[debug] waiting for P(repair_dmg_critical.png) S: 0.95 to appear
[debug] P(repair_dmg_critical.png) S: 0.95 has appeared.
[log] CLICK on L(1045,272)@S(0)[0,0 1366x768]
←[92m[2015-10-07 12:40:37] Starting repair on critically damaged ship!←[0m
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has appeared.
[debug] OCR data path: D:/sikuli/libs/
[debug] TextRecognizer: inited.
[debug] Region.text: #(01:47:10)#
←[92m[2015-10-07 12:40:41] Repair should be done at 2015-10-07 14:27:41←[0m
[debug] waiting for repair_start.png to appear
[debug] repair_start.png has appeared.
[debug] waiting for repair_start.png to appear
[debug] repair_start.png has appeared.
[log] CLICK on L(997,569)@S(0)[0,0 1366x768]
[debug] waiting for repair_start_confirm.png to appear
[debug] repair_start_confirm.png has appeared.
[debug] waiting for repair_start_confirm.png to appear
[debug] repair_start_confirm.png has appeared.
[log] CLICK on L(814,532)@S(0)[0,0 1366x768]
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[log] CLICK on L(565,377)@S(0)[0,0 1366x768]
←[94m[2015-10-07 12:40:48] Check for critically damaged ships.←[0m
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has not appeared.
[error] script stopped with error in line 349
[error] FindFailed ( can not find repair_timer.png on the screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)
```

well this happens when there are two heavy damaged ships to repair on the fleet but idk why it this happens
happened 2 times only for the last 5 
hours
