### ISSUE TITLE
Unable to start kancolle-auto

### ISSUE THREAD

**Issue by nekoma0** [mrmin123/kancolle-auto#226]
_Please read the FAQ/Common Issues section of the README before opening a ticket. If you are submitting a feature request or a non-bug report, please feel free to delete this template. Also feel free to delete sections of this template you do not find relevant when submitting a bug report. Thanks!_
#### Environment details
- kancolle-auto version (last modified date): kancolle-auto-5
- Viewer/browser: Chrome
- Operating system: Windows 10
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [x] Consistent
- [ ] Transient

I follow the Installation Wiki.
I am using the following programs.
Python 2.7.12
Java JRE 8
Sikuli 1.0.1 with option 2 and 5. (tessdata folder is available)
#### Console log (if applicable)

```
L:\Kancolle>afk.bat
[2016-08-26 22:47:15] Reading config file
[2016-08-26 22:47:15] Expeditions (fleet 2: 2, fleet 3: 21, fleet 4: 38) enabled!
[2016-08-26 22:47:15] Combat enabled!
[2016-08-26 22:47:15] Config loaded!
[2016-08-26 22:47:15] Reading config file
[2016-08-26 22:47:15] Starting kancolle_auto
[2016-08-26 22:47:15] Finding window!
[2016-08-26 22:47:15] Focus on KanColle!
[log] App.focus Google Chrome(0) #0
[error] script stopped with error in line 383
[error] AttributeError ( 'NoneType' object has no attribute 'x' )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(JythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScriptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunner.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunner.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)

L:\Kancolle>
```
#### Relevant config snippet (if applicable)

```
###########################################################################
# ============================= IMPORTANT!! ============================= #
# Please refer to the wiki pages for guidance on setting up this file!:   #
# Detailed explanation of config file:                                    #
#   https://github.com/mrmin123/kancolle-auto/wiki/Setup-config.ini       #
# Example configs:                                                        #
#   https://github.com/mrmin123/kancolle-auto/wiki/Example-configs        #
#   https://github.com/mrmin123/kancolle-auto/wiki/Example-Event-configs  #
###########################################################################

[General]
# The program/window name of your Kancolle container. Examples include Google Chrome,
# Firefox, KanColleViewer!, KanColleTool Viewer, Electronic Observer, etc...
# WARNING: IF YOU ARE USING A VIEWER WITH SUBTITLES, AND USING THE COMBAT MODULE, EITHER DISABLE
# THE SUBTITLES OR LOWER THEIR FONT SIZE TO 13PX OR LOWER. YOU MAY LOSE SHIPS IF YOU DO NOT DO
# THIS. PLEASE REFER TO THE FAQ IN THE README FOR DETAILS
Program: Google Chrome

# Which built-in recovery method to use when you get catbomb'ed. Valid options are Browser,
# KC3, KCV, KCT, and EO.
RecoveryMethod: KC3

# Your machine's timezone's difference to JST in full hours. Relevant to the Quests and PvP
# modules. Default is 0, same timezone as JST.
JSTOffset: 0

# How often kancolle-auto should run its loop, specified in full seconds. A lower value will make
# kancolle-auto be quicker to respond to timers, while a higher value will make it slower, but
# perhaps guard against bot-detection. Default value is 20.
SleepCycle: 15

# Specifies the desired # of menus to randomly walk through. The number of sidesteps range from 0
# to the Paranoia value. Setting this value to at least 1 is recommended (0 to 1 sidesteps).
Paranoia: 3

# If you have a slow computer/network connection, you may encounter frequent FindFailed errors.
# Increase this value by whole numbers (seconds) to increase the length of all sleep/wait timers
# to avoid this. Default is 0.
SleepModifier: 2


[ScheduledSleep]
# Set to True if you want kancolle-auto to automatically sleep/pause at set times. Highly
# recommended that you set this to True if you intend to run kancolle-auto for a long period of
# time.
Enabled: False

# Define around when you would like schedule sleep to start, in military time. Default time is
#0030, meaning that Schedule Sleep will begin sometimes between 12:30AM and 1AM. Relative to your
# computer's time.
StartTime: 0030

# How long you want the sleep to last, in hours (decimals are OK). Anywhere between 0 to 10 minutes
# are added randomly to the actual timer. Default value is 3.5 (hours).
SleepLength: 3.5


[ScheduledStop]
# Set to True if you want kancolle-auto to automatically stop and exit after a set number of hours,
# expeditions, sorties, or PvPs. You will have to manually restart kancolle-auto after this.
Enabled: False

# Define what you want to base the stop count on. Valid options are 'time', 'expedition', 'sortie',
# and 'pvp'.
Mode: time

# Define how many of the above kancolle-auto should perform before automatically stopping.
Count: 5


[Expeditions]
# Set to True if you want kancolle-auto to run expeditions; False if not.
Enabled: True

# Define which Expedition a fleet should go on. If you do not have a Fleet unlocked
# or you don't want it to run an expedition, just leave its value blank.
Fleet2: 2
Fleet3: 21
Fleet4: 38


[PvP]
# Set to True if you want Fleet 1 to run PvP sorties; False if not. NOTE: line-ahead formation
# will be selected for everything, regardless of enemy fleet...
Enabled: False

# Specify which saved fleet composition should be used for PvP, with the first saved fleet being 1.
# NOTE: this value is only relevant if both PvP and Combat modules are enabled with different
# fleets assigned to them! Setting the FleetComp value to 0 for either module, or setting them to
# the same value will disable the fleet composition switcher.
FleetComp: 1


[Combat]
# Set to True if you want Fleet 1 to run combat sorties; False if not.
Enabled: True

# Specify which saved fleet composition should be used for Combat, with the first saved fleet
# being 1.
# NOTE: this value is only relevant if both PvP and Combat modules are enabled with different
# fleets assigned to them! Setting the FleetComp value to 0 for either module, or setting them to
# the same value will disable the fleet composition switcher.
FleetComp: 0

# Set which area you want to sortie to.
# Example 1: if you're running 3-2-A, set this to '3'
# Example 2: if you're running 2-3 (Orel), set this to '2'
# Example 3: if you're running Events, set this to 'E'
Area: 2

# Set which subarea you want to sortie to.
# Example 1: if you're running 3-2-A, set this to '2'
# Example 2: if you're running 2-3 (Orel), set this to '3'
# Example 3: if you're running the first map (1) of the second screen of maps (2) in the Event
#   screen, set this to '2-1'
Subarea: 3

# Specify whether the map you're running utilizes Combined Fleets or not. Only relevant for Events.
# Will automatically handle FCFs and the extra ships needing repairs + resupplies. This also turns
# off PvP and Fleet 2's Expedition, regardless of what you input above.
CombinedFleet: False

# Maximum number of combat nodes to run. Resource/hazard nodes do not count.
# Example 1: if you're running 3-2-A, set this to '1' (1st node only)
# Example 2: if you're running 2-3 (Orel), set this to '3' or above
Nodes: 3

# If the map you are sortieing to involves node selections, use this to point at the image
# generated for that specific node. For example, if you want to always head to node K on E-3 of
# Winter 2016, set this to '_node_E-3-K' to reference the '_node_E-3-K.png' image included.
# For other maps, please generate this image yourself (a 70px x 70px image of the node during
# node selection, with the desired node being in the center of the image).
NodeSelects:

# Formations to use at each combat node, separated by commas. Valid options are
# line_ahead, double_line, diamond, echelon, or line_abreast. If the number of
# formations you've specified does not match the number of nodes you specified above,
# the script will default to line_ahead for the remaining nodes.
# Example 1: if you're running 3-2-A, set this to 'line_ahead'
# Example 2: if you're running 2-3 (Orel), set this to 'line_ahead' (remaining nodes
#     defaults to 'line_ahead')
# For combined fleets, the valid options are combinedfleet_1, combinedfleet_2, combinedfleet_3,
# combinedfleet_4, in order of how they show up in the formation selection screen (left to right,
# top to bottom).
Formations: line_ahead

# Whether or not to engage in night battle at each combat node, separated by commas.
# Valid options are True (to engage in night battle) and False (to avoid night battle).
# If the number of night battle options you've specified does not match the number of
# nodes you specified above, the script will default to True for the remaining nodes.
# Example 1: if you're running 3-2-A, set this to 'False'
# Example 2: if you're running 2-3 (Orel), set this to 'False' (remaining nodes defaults
#     to 'True')
NightBattles: False

# Set the damage threshold for your ships. RetreatLimit specifies when sortie should be cancelled
# (retreat from sortie), and RepairLimit specifies which ships should be repaired before
# sortieing again. In addition, the tool will automatically not sortie if any ships are at the
# RepairLimit threshold. 0 = light damage, 1 = moderate damage, 2 = critical damage.
# Example: If you want the script to retreat when any ship is at critical damage, but also repair
#     any ships at moderate damage, set RetreatLimit to 2, RepairLimit to 1.
RetreatLimit: 2
RepairLimit: 1

# Set the repair time limit for repairs. kancolle-auto will automatically use a bucket to repair a
# ship if its repair time is above this # of hours. Integer values only, please. If you want to
# never use buckets, set this to '9900'. A limit of '9500' and below will allow the repair script
# to use a bucket if the OCR cannot properly read the timer, so adjust this accordingly. If you
# always want to use buckets, set it to '0'.
RepairTimeLimit: 0030

# Whether or not to find submarines under repair to switch out so kancolle-auto can continue
# sorties. Useful for maps where submarines are used to tank hits, such as 2-3 (Orel) or 3-2-A.
SubmarineSwitch: True

# Whether or not to consider fatigue/morale before sorties. If the ships have an unhappy face
# (morale of 29 or below) the script will wait for a set amount of time for morale to recover.
CheckFatigue: True

# Whether or not to sortie when the port (ship slots) is full. Set to True if you do not want
# sorties to occur when your port is full. Port checking is automatically done when sortieing to
# Event maps, since sortieing is prohibited when you do not have 5 free ship slots.
PortCheck: False

# Set this to True if you want kancolle-auto to stop sortieing to the specified map once the medal
# has been obtained. Only applicable to the monthly EOs (1-5, 2-5, 3-5, 4-5, 5-5).
MedalStop: False

# Set whether or not to 'push' past the max number of defined combat nodes, REGARDLESS OF THE
# STATE OF YOUR FLEET. Only do this if the last node is a resource/non-combat node, like the end
# of 1-6, and only if your path is 100% fixed!
# WARNING: YOU MAY LOSE SHIPS WITH THIS SET TO TRUE. PLEASE STUDY THE MAP YOU ARE SORTIEING TO AND
# MAKE AN EDUCATED DECISION
LastNodePush: False


[LBAS]
# Set to True if you want kancolle-auto to sortie with LBAS support
Enabled: False

# Enabled air support groups for the sortie, delimited by commas. Values should be 1, 2, or 3
EnabledGroups:

# Node image names for each of the above enabled air support groups. Groups with node targets
# should have two nodes assigned to them. You'll have to generate these images yourself (or wait
# for the program to be updated on Github). Active groups with no node images are assumed to be
# air defense groups, and will be resupplied each sortie, but not assigned nodes on the map
Group1Nodes:
Group2Nodes:
Group3Nodes:


[Quests]
# Set to True if you want kancolle-auto to manage quests; False if not.
Enabled: True

# Quests to check for. Please check the Wiki linked above for a list of supported quests. Defaults
# to a list of most generic quests. kancolle-auto will ignore quests if they are not completable
# as specified by your config (if PvP is disabled, PvP quests will not be activated, and so on).
Quests: bd1, bd2, bd3, bd4, bd5, bd6, bd7, bd8, bw1, bw2, bw3, bw4, bw5, bw6, bw7, c2, c3, c4, c8, d2, d3, d4, d9, d11, e3, e4

# How often should quests be checked? Settings this to 1 will make quests be checked after every
# expedition and sortie. Default is 3.
CheckSchedule: 3

```

**Comment by mrmin123** [comment]
kancolle-auto/Sikuli isn't finding Google Chrome. Do you have multiple monitors? Sikuli can only identify windows on your primary monitor.

**Comment by nekoma0** [comment]
yes, i have multiple monitors, but even if i drag it to primary monitors, it still doesn't detect

**Comment by tigurand** [comment]
I have this problem lately after windows 10 anniversary update. Try to click anywhere on kancolle tab on chrome right after you launch kancolle auto, it worked for me.

**Comment by nekoma0** [comment]
Thanks tigurand. Your solution saved me.
Before this, i was still brain storming as i couldn't figure out why, because when i launch kancolle auto, it did auto select and focus on the window, but as soon as that happen. it triggers this
[error] script stopped with error in line 383
[error] AttributeError ( 'NoneType' object has no attribute 'x' )

I did what you say, as soon as i launch kancolle auto, i immediately click upon google chrome, and BAM!, the mouse move itself and it's working magically.

Thanks guys

**Comment by mrmin123** [comment]
Thanks for the solution. I'll have to update the readme/wiki next time with this info. Closing for now.
