### ISSUE TITLE
Troubleshooting: [error] script stopped with error in line 515

### ISSUE THREAD

**Issue by Kusoteitoku123241** [mrmin123/kancolle-auto#239]
[x] Consistent
The script crashes every time a bit after it focuses on the game window.

C:\WINDOWS\system32>java -jar C:\Kancolle-auto\Sikuli\sikuli-script.jar -r C:\Kancolle-auto\kancolle-auto-master\kancolle_auto.sikuli
[2016-11-16 18:00:01] Reading config file!
[2016-11-16 18:00:01] Expeditions enabled: fleet 2: 2, fleet 3: 5, fleet 4: 6
[2016-11-16 18:00:01] Combat enabled (sortie mode): sortieing to 2-3
[2016-11-16 18:00:01] Submarine Switch enabled
[2016-11-16 18:00:01] Reading util config file!
[2016-11-16 18:00:01] Config successfully loaded!
[2016-11-16 18:00:01] Starting kancolle_auto!
[2016-11-16 18:00:01] Finding window!
[2016-11-16 18:00:01] Focus on KanColle!
[log] App.focus KanColleViewer!(0) #0
[error] script stopped with error in line 515
[error] AttributeError ( 'NoneType' object has no attribute 'x' )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(JythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScriptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunner.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunner.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)

Running as admin (it wouldn't even start otherwise), Windows10.
Any help is greatly appreciated, please let me know if you need more infos!

**Comment by n0k0m3** [comment]
Move the mouse to Chrome windows/out of cmd box after execute the code

On Wed, Nov 16, 2016 at 12:04 PM Kusoteitoku123241 notifications@github.com
wrote:

The script crashes a bit after it focuses on the game window.

C:\WINDOWS\system32>java -jar C:\Kancolle-auto\Sikuli\sikuli-script.jar -r
C:\Kancolle-auto\kancolle-auto-master\kancolle_auto.sikuli
[2016-11-16 18:00:01] Reading config file!
[2016-11-16 18:00:01] Expeditions enabled: fleet 2: 2, fleet 3: 5, fleet 4:
6
[2016-11-16 18:00:01] Combat enabled (sortie mode): sortieing to 2-3
[2016-11-16 18:00:01] Submarine Switch enabled
[2016-11-16 18:00:01] Reading util config file!
[2016-11-16 18:00:01] Config successfully loaded!
[2016-11-16 18:00:01] Starting kancolle_auto!
[2016-11-16 18:00:01] Finding window!
[2016-11-16 18:00:01] Focus on KanColle!
[log] App.focus KanColleViewer!(0) #0
[error] script stopped with error in line 515
[error] AttributeError ( 'NoneType' object has no attribute 'x' )
Exception in thread "main" java.lang.IllegalStateException: No match found
at java.util.regex.Matcher.group(Unknown Source)
at
org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(JythonScriptRunner.java:326)
at
org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScriptRunner.java:290)
at
org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunner.java:200)
at
org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunner.java:162)
at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/mrmin123/kancolle-auto/issues/239, or mute the thread

**Comment by Kusoteitoku123241** [comment]
I tried, having KCV on the main screen and the cmd on the second screen, started outputting
[log] App.focus KanColleViewer!(0) #0
[log] TYPE "#ESC."

Over and over again

C:\WINDOWS\system32>java -jar C:\Kancolle-auto\Sikuli\sikuli-script.jar -r C:\Kancolle-auto\kancolle-auto-master\kancolle_auto.sikuli
[2016-11-16 18:10:38] Reading config file!
[2016-11-16 18:10:38] Expeditions enabled: fleet 2: 2, fleet 3: 5, fleet 4: 6
[2016-11-16 18:10:38] Combat enabled (sortie mode): sortieing to 2-3
[2016-11-16 18:10:38] Submarine Switch enabled
[2016-11-16 18:10:38] Reading util config file!
[2016-11-16 18:10:38] Config successfully loaded!
[2016-11-16 18:10:38] Starting kancolle_auto!
[2016-11-16 18:10:38] Finding window!
[2016-11-16 18:10:38] Focus on KanColle!
[log] App.focus KanColleViewer!(0) #0
[log] App.focus KanColleViewer!(0) #0
[log] TYPE "#ESC."
[log] App.focus KanColleViewer!(0) #0
[log] TYPE "#ESC."
[log] App.focus KanColleViewer!(0) #0
[log] TYPE "#ESC."
[log] App.focus KanColleViewer!(0) #0
[log] TYPE "#ESC."
[log] App.focus KanColleViewer!(0) #0
[log] TYPE "#ESC."
[log] App.focus KanColleViewer!(0) #0
[log] TYPE "#ESC."

**Comment by n0k0m3** [comment]
Resize KCV to 100%, minimize other plugins on KCV if needed. This script
only work with original (100%) scaled KC frame

**Comment by Kusoteitoku123241** [comment]
Works wonderfully, thank you a lot!
