### ISSUE TITLE
Repair error

### ISSUE THREAD

**Issue by AppleBoi86** [mrmin123/kancolle-auto#50]
Hello mrmin123, I just bump into this. I choose to repair when moderate damage and use buckets.

---

[94m[2015-10-14 07:30:24] Navigating to Repair menu![0m
[log] CLICK on L(884,384)@S(0)[0,0 1600x900]
[log] CLICK on L(1015,185)@S(0)[0,0 1600x900]
[94m[2015-10-14 07:30:34] Check for critically damaged ships.[0m
[94m[2015-10-14 07:30:37] Check for moderately-damaged ships.[0m
[log] CLICK on L(1495,158)@S(0)[0,0 1600x900]
[92m[2015-10-14 07:30:38] Starting repair on moderately damaged ship![0m
[error] script stopped with error in line 345
[error] ValueError ( invalid literal for int() with base 10: 0S )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)
        at org.sikuli.ide.SikuliIDE.main(SikuliIDE.java:212)

**Comment by kevin01523** [comment]
thats an ocr error.well does it always happen?

**Comment by mrmin123** [comment]
It probably doesn't happen often, but it's an easy fix. S -> 5 is my guess. I'll upload a fix for this tonight.
