### ISSUE TITLE
[error] FindFailed ( can not find top_menu_return.png on the screen. )

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#56]
```
D:\sikuli>runScript -d 2 -r kancolle_auto.sikuli
+++ running this Java
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) Client VM (build 25.60-b23, mixed mode)
+++ trying to start Sikuli Script
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
D:\sikuli\sikuli-script.jar -d 2 -r kancolle_auto.sikuli
[debug] Running on Java 8 (1.8.0_60-b27)
[debug] ResourceLoaderBasic: check: we are running on arch: x86
[debug] ResourceLoaderBasic: check: using Java at: C:/Program Files/Java/jre1.8.
0_60/
[debug] Screen: initScreens: basic initialization (1 Screen(s) found)
←[94m[2015-10-17 11:57:01] Reading config file←[0m
←[92m[2015-10-17 11:57:02] Expeditions enabled!←[0m
←[92m[2015-10-17 11:57:02] Combat enabled!←[0m
←[92m[2015-10-17 11:57:02] Config loaded!←[0m
←[92m[2015-10-17 11:57:02] Starting kancolle_auto←[0m
←[94m[2015-10-17 11:57:02] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-10-17 11:57:10] At Home!←[0m
←[94m[2015-10-17 11:57:10] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-17 11:57:13] No, no fleets to receive!←[0m
←[92m[2015-10-17 11:57:13] Refreshing Home!←[0m
[debug] waiting for quests_main.png to appear
[debug] quests_main.png has appeared.
[log] CLICK on L(868,191)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(365,589)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(365,589)@S(0)[0,0 1366x768]
←[92m[2015-10-17 11:57:37] At Home!←[0m
←[94m[2015-10-17 11:57:37] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-17 11:57:41] No, no fleets to receive!←[0m
←[94m[2015-10-17 11:57:41] Navigating to Expedition menu!←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(506,407)@S(0)[0,0 1366x768]
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[log] CLICK on L(980,377)@S(0)[0,0 1366x768]
[debug] waiting for expedition_screen_ready.png to appear
[debug] expedition_screen_ready.png has appeared.
←[94m[2015-10-17 11:57:46] Let's send an expedition out!←[0m
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[log] CLICK on L(442,574)@S(0)[0,0 1366x768]
[debug] waiting for ensei_name_05.png to appear
[debug] ensei_name_05.png has appeared.
[debug] waiting for ensei_name_05.png to appear
[debug] ensei_name_05.png has appeared.
[log] CLICK on L(606,432)@S(0)[0,0 1366x768]
[debug] waiting for expedition_timer.png to appear
[debug] expedition_timer.png has appeared.
[debug] OCR data path: D:/sikuli/libs/
[debug] TextRecognizer: inited.
[debug] Region.text: #(00:34:59)#
←[93m[2015-10-17 11:58:05] Expedition is already running: Expedition 5 (ETA 2015
-10-17 12:33:05)←[0m
←[94m[2015-10-17 11:58:05] Let's send an expedition out!←[0m
[debug] waiting for ensei_area_05.png to appear
[debug] ensei_area_05.png has appeared.
[debug] waiting for ensei_area_05.png to appear
[debug] ensei_area_05.png has appeared.
[log] CLICK on L(674,575)@S(0)[0,0 1366x768]
[debug] waiting for ensei_name_38.png to appear
[debug] ensei_name_38.png has appeared.
[debug] waiting for ensei_name_38.png to appear
[debug] ensei_name_38.png has appeared.
[log] CLICK on L(601,463)@S(0)[0,0 1366x768]
[debug] waiting for expedition_timer.png to appear
[debug] expedition_timer.png has appeared.
[debug] Region.text: #(02:01:13)#
←[93m[2015-10-17 11:58:19] Expedition is already running: Expedition 38 (ETA 201
5-10-17 14:00:19)←[0m
←[94m[2015-10-17 11:58:19] Let's send an expedition out!←[0m
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[log] CLICK on L(442,574)@S(0)[0,0 1366x768]
[debug] waiting for ensei_name_06.png to appear
[debug] ensei_name_06.png has appeared.
[debug] waiting for ensei_name_06.png to appear
[debug] ensei_name_06.png has appeared.
[log] CLICK on L(605,462)@S(0)[0,0 1366x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(984,582)@S(0)[0,0 1366x768]
←[94m[2015-10-17 11:58:28] Trying to send out fleet 4 for expedition 6←[0m
[debug] waiting for fleet_4.png to appear
[debug] fleet_4.png has appeared.
[debug] waiting for fleet_4.png to appear
[debug] fleet_4.png has appeared.
[log] CLICK on L(759,257)@S(0)[0,0 1366x768]
←[94m[2015-10-17 11:58:34] Checking expedition fleet status!←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for ensei_start.png to appear
[debug] ensei_start.png has appeared.
[debug] waiting for ensei_start.png to appear
[debug] ensei_start.png has appeared.
[log] CLICK on L(932,584)@S(0)[0,0 1366x768]
[debug] waiting for exp_started.png to appear
[debug] exp_started.png has appeared.
←[92m[2015-10-17 11:58:45] Expedition sent!: Expedition 6 (ETA 2015-10-17 12:38:
10)←[0m
←[94m[2015-10-17 11:58:47] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-17 11:58:57] Going Home!←[0m
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(378,397)@S(0)[0,0 1366x768]
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
←[92m[2015-10-17 11:59:00] At Home!←[0m
←[94m[2015-10-17 11:59:00] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-17 11:59:04] No, no fleets to receive!←[0m
←[94m[2015-10-17 11:59:04] Navigating to Sortie menu!←[0m
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(506,407)@S(0)[0,0 1366x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(540,377)@S(0)[0,0 1366x768]
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[log] CLICK on L(540,579)@S(0)[0,0 1366x768]
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[log] CLICK on L(567,488)@S(0)[0,0 1366x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(992,582)@S(0)[0,0 1366x768]
←[94m[2015-10-17 11:59:20] Checking fleet condition...←[0m
←[94m[2015-10-17 11:59:29] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
←[94m[2015-10-17 11:59:36] Checking fleet morale!←[0m
←[92m[2015-10-17 11:59:42] Ships have good morale!←[0m
←[92m[2015-10-17 11:59:46] Commencing sortie!←[0m
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(937,583)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(643,384)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:00:10] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.95 to appear
[debug] P(formation_line_ahead.png) S: 0.95 has appeared.
[log] CLICK on L(754,323)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:00:48] Selecting fleet formation!←[0m
←[94m[2015-10-17 12:02:34] Declining night battle!←[0m
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(599,378)@S(0)[0,0 1366x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:02:54] Checking fleet condition...←[0m
←[94m[2015-10-17 12:03:03] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[log] CLICK on L(601,377)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(643,384)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:03:45] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.95 to appear
[debug] P(formation_line_ahead.png) S: 0.95 has appeared.
[log] CLICK on L(754,323)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:03:58] Selecting fleet formation!←[0m
←[94m[2015-10-17 12:05:12] Declining night battle!←[0m
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(599,378)@S(0)[0,0 1366x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:05:27] Checking fleet condition...←[0m
←[94m[2015-10-17 12:05:37] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[log] CLICK on L(1067,579)@S(0)[0,0 1366x768]
←[92m[2015-10-17 12:06:13] Sortie complete!←[0m
←[94m[2015-10-17 12:06:13] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-10-17 12:06:22] At Home!←[0m
←[94m[2015-10-17 12:06:22] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-17 12:06:26] No, no fleets to receive!←[0m
←[92m[2015-10-17 12:06:26] Refreshing Home!←[0m
[debug] waiting for quests_main.png to appear
[debug] quests_main.png has appeared.
[log] CLICK on L(868,191)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(365,589)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(365,589)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has not appeared.
←[91m[2015-10-17 12:07:06] Non-catbomb script crash, or catbomb script crash w/
unsupported Viewer!←[0m
FindFailed: can not find top_menu_return.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 390
[error] FindFailed ( can not find top_menu_return.png on the screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)

D:\sikuli>
```

**Comment by kevin01523** [comment]
```
←[92m[2015-10-17 12:22:35] At Home!←[0m
←[94m[2015-10-17 12:22:35] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-17 12:22:39] No, no fleets to receive!←[0m
←[92m[2015-10-17 12:22:39] Refreshing Home!←[0m
[debug] waiting for quests_main.png to appear
[debug] quests_main.png has appeared.
[log] CLICK on L(868,191)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(365,589)@S(0)[0,0 1366x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(365,589)@S(0)[0,0 1366x768]
←[92m[2015-10-17 12:23:02] At Home!←[0m
←[94m[2015-10-17 12:23:02] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-17 12:23:06] No, no fleets to receive!←[0m
←[94m[2015-10-17 12:23:06] Navigating to Sortie menu!←[0m
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(506,407)@S(0)[0,0 1366x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(540,377)@S(0)[0,0 1366x768]
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[log] CLICK on L(540,579)@S(0)[0,0 1366x768]
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[log] CLICK on L(567,488)@S(0)[0,0 1366x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(992,582)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:23:21] Checking fleet condition...←[0m
←[94m[2015-10-17 12:23:31] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
←[94m[2015-10-17 12:23:37] Checking fleet morale!←[0m
←[92m[2015-10-17 12:23:44] Ships have good morale!←[0m
←[92m[2015-10-17 12:23:47] Commencing sortie!←[0m
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(937,583)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(643,384)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:24:14] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.95 to appear
[debug] P(formation_line_ahead.png) S: 0.95 has appeared.
[log] CLICK on L(754,323)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:24:52] Selecting fleet formation!←[0m
←[94m[2015-10-17 12:25:45] Declining night battle!←[0m
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(599,378)@S(0)[0,0 1366x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:26:01] Checking fleet condition...←[0m
←[94m[2015-10-17 12:26:11] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[log] CLICK on L(1067,579)@S(0)[0,0 1366x768]
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[log] CLICK on L(601,377)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(643,384)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:27:20] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.95 to appear
[debug] P(formation_line_ahead.png) S: 0.95 has appeared.
[log] CLICK on L(754,323)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:27:34] Selecting fleet formation!←[0m
←[94m[2015-10-17 12:28:28] Declining night battle!←[0m
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(599,378)@S(0)[0,0 1366x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
←[94m[2015-10-17 12:28:43] Checking fleet condition...←[0m
←[94m[2015-10-17 12:28:53] Light damage: 0; moderate damage: 0; critical damage:
 0←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1060,570)@S(0)[0,0 1366x768]
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[log] CLICK on L(1067,579)@S(0)[0,0 1366x768]
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has not appeared.
←[91m[2015-10-17 12:30:10] Non-catbomb script crash, or catbomb script crash w/
unsupported Viewer!←[0m
FindFailed: can not find combat_nextnode.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 425
[error] FindFailed ( can not find combat_nextnode.png on the screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)
```

more cannot find error but not catbomb 
error occured after it got back from sortie and stopped at home

the log above also stopped when its on home screen

**Comment by mrmin123** [comment]
I think both of these are all related to timers/delays. In the first case, it clicked on top_menu_return.png, but sortie.png didn't appear within 2-4 seconds, so it crashed. In the second case, after pressing next_alt.png for the second time, the Home page didn't appear within 3-6 seconds, so it crashed.

if you're seeing delays between screens in your game that seem to be longer than the sleeps specified in the script, try going in and modifying the sleep timers or the `sleep()` method in `util.py` to increase the lower limit of all timers. These might be specific to your game/connection.

**Comment by kevin01523** [comment]
ok ill try it mostly i experience this when im using windows.im testing it now with kct and the get api link works http://cache.coburnsdomain.com/kct/KanColleTool_0.9.6.zip this is the latest version the on on their download link is not updated you have to enable the cookie hack 1st it automatically switch to jp language

**Comment by mrmin123** [comment]
@kevin01523 Ah, ok. I saw your message in the other thread but didn't have a chance to test yet. I'm testing the randomized mouse click locations right now.

**Comment by kevin01523** [comment]
ok this one is odd after going to fleet compo screen it searched for the wrong back button? wrong image file name?

[2015-10-20 03:14:28] At Home!
[2015-10-20 03:14:28] Are there returning expeditions to receive?
[debug] waiting for menu_top_profile.png to appear
[debug] menu_top_profile.png has appeared.
[2015-10-20 03:14:33] No, no fleets to receive!
[2015-10-20 03:14:33] Refreshing Home!
[debug] waiting for menu_main_fleetcomp.png to appear
[debug] menu_main_fleetcomp.png has appeared.
[debug] waiting for P(menu_main_fleetcomp.png) S: 0.8 T: -15,-28 to appear
[debug] P(menu_main_fleetcomp.png) S: 0.8 T: -15,-28 has appeared.
[log] CLICK on L(442,234)@S(0)[0,0 1360x768]
[debug] waiting for menu_top_home.png to appear
[debug] menu_top_home.png has not appeared.
[2015-10-20 03:15:00] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: can not find menu_top_home.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 429
[error] FindFailed ( can not find menu_top_home.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
62: util (  wait_and_click )     kc_window.wait(pic, time)
84: main (  go_home )     wait_and_click(kc_window, 'menu_top_home.png', 10)
250: main (  sortie_action )     go_home()
420: main (  <module> )     sortie_action()
[error] --- Traceback --- end --------------
kevin@LinuxMint ~/KanColleTool $

**Comment by mrmin123** [comment]
@kevin01523 Try increasing the sleep timer on line 76 of kancolle_auto.py. The code seems to be looking for `menu_top_home.png` because `menu_side_home.png` doesn't appear within 3-6 seconds after pressing `menu_main_fleetcomp.png` (these should all be valid filenames)

**Comment by mrmin123** [comment]
@kevin01523 or maybe change the custom `sleep()` method in `util.py` so it's `tsleep(uniform(sec, sec * 2) + 2)` or something to increase all sleep timers :p

**Comment by mrmin123** [comment]
Also thanks, the cookie hack + 0.9.6 worked for KCT.

**Comment by mrmin123** [comment]
Closing issue for now.
